spring.application.name=cloudj-backend

# Test filePath
filePath=/home/cmilo/Projects/cloudj/cloudj-backend/src/test/stored-file

# Configuring upload file limits
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB
