spring.application.name=cloudj-backend

# AWS Configuration
cloud.aws.credentials.access-key=${aws-secret-key-id}
cloud.aws.credentials.secret-key=${aws-secret-key}
cloud.aws.region.static=${aws-region}
aws.bucket.name=${aws-bucket-name}

# PostgreSQL config
spring.datasource.url=${datasource-url}
spring.datasource.username=${datasource-username}
# ill set up a password later :o
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT config
app.jwt.secret=${jwt-secret}
app.jwt.issuer=cloudj.com
app.jwt.expiration=${jwt-expiration}
app.jwt.refresh-expiration=${jwt-refresh-expiration}