spring.application.name=cloudj-backend

# Configuring upload file limits
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# AWS Configuration
cloud.aws.credentials.access-key=${aws-access-key}
cloud.aws.credentials.secret-key=${aws-secret-key}
cloud.aws.region.static=${aws-region}
aws.bucket.name=${aws-bucket-name}
